import unittest
from unittest.mock import MagicMock, patch
import sys
import os

# Add src to path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../')))

from src.tools.lookup import LookupToolSet

class TestEnhancedTools(unittest.TestCase):
    def setUp(self):
        self.mock_retriever = MagicMock()
        self.lookup_tools = LookupToolSet(self.mock_retriever)

    def test_navigation_reflector(self):
        # Setup mocks
        self.mock_retriever.search.return_value = [
            {"payload": {"path": "Chapter 1/1.1"}},
            {"payload": {"path": "Chapter 2/2.1"}}
        ]
        self.mock_retriever.search_by_path.return_value = [
            {"path": "Chapter 1/1.1"}, # Duplicate
            {"path": "Chapter 3/3.1"}
        ]

        # Execute
        result = self.lookup_tools.Navigation_Reflector("some query")

        # Verify
        self.assertIn("Chapter 1/1.1", result)
        self.assertIn("Chapter 2/2.1", result)
        self.assertIn("Chapter 3/3.1", result)
        # Check uniqueness implicitly by counting lines or similar, but assertIn is good for now.
        lines = result.split('\n')
        self.assertEqual(len(lines), 3) # Should be 3 unique paths

    def test_context_expander(self):
        # Setup mocks
        self.mock_retriever.get_context.return_value = [
            {"chunk_id": 10, "text": "Prev content", "path": "p1"},
            {"chunk_id": 11, "text": "Target content", "path": "p1"},
            {"chunk_id": 12, "text": "Next content", "path": "p1"}
        ]

        # Execute
        result = self.lookup_tools.Context_Expander(11)

        # Verify
        self.assertIn("[Chunk ID: 10]", result)
        self.assertIn("Prev content", result)
        self.assertIn("[Chunk ID: 11]", result)
        self.assertIn("Target content", result)
        self.assertIn("[Chunk ID: 12]", result)
        self.assertIn("Next content", result)

    @patch('src.tools.lookup.get_llm')
    def test_summarization_trigger(self, mock_get_llm):
        # Setup huge text
        huge_text = "a" * 3000
        
        # Setup mocks
        mock_llm_instance = MagicMock()
        mock_get_llm.return_value = mock_llm_instance
        
        # We need distinct responses for Reranking vs Summarization vs Reporting
        # 1. Rerank: Score 9
        # 2. Summarize: Summary text
        # 3. Report: Final report (not used here as len=1)
        mock_llm_instance.invoke.side_effect = [
            MagicMock(content="Score: 9"),       # Rerank
            MagicMock(content="Summary text"),   # Summarize
            MagicMock(content="Final report with Summary text") # Report
        ]
        
        self.mock_retriever.search.return_value = [
            {"id": 1, "payload": {"text": huge_text}}
        ]

        # Execute
        result = self.lookup_tools.semantic_fallback("query")

        # Verify
        # The result should be the summary generated by LLM
        self.assertIn("Summary text", result)
        self.assertIn("[Note: This is a summary", result)

    def test_no_summarization_for_short_text(self):
        # Setup short text
        short_text = "Short text"
        
        self.mock_retriever.search.return_value = [
            {"id": 1, "payload": {"text": short_text}}
        ]

        # Execute
        with patch('src.tools.lookup.get_llm') as mock_get_llm:
            mock_llm_instance = MagicMock()
            mock_get_llm.return_value = mock_llm_instance
            
            # 1. Rerank: Score 9
            mock_llm_instance.invoke.side_effect = [
                MagicMock(content="Score: 9")
            ]
            
            result = self.lookup_tools.semantic_fallback("query")
            
            # Verify
            # get_llm IS called for reranking
            assert mock_get_llm.called
            
            # But we want to ensure summarization wasn't triggered.
            # Summarization happens if len(text) > 2000.
            # We can check call count. 
            # If summarization was called, invoke would be called 2 times (Rerank, Summarize).
            # If not, 1 time (Rerank).
            self.assertEqual(mock_llm_instance.invoke.call_count, 1)
            
            self.assertIn("Short text", result)

if __name__ == '__main__':
    unittest.main()
